# Generated by Django 4.0.6 on 2023-07-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotapp', '0002_alter_buser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
